name 'puppet-amavisd'
version '0.1.0'
source 'git://github.com/Savar/puppet-amavisd.git'
author 'mobile.international GmbH'
license 'Apache 2.0'
summary 'Amavisd module'
description 'Amavisd module'
project_page 'http://github.com/Savar/puppet-amavisd'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
